spring:
  datasource:
    source:
      name: source
      jdbc-url: jdbc:sqlserver://172.20.20.1:1433;DatabaseName=Runtime
      username: sa
      password: Zsb83887154
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    target:
      name: target
      jdbc-url: jdbc:oracle:thin:@172.20.20.2:1523:orcl
      username: dbo_donghu_portal
      password: donghu87775236
      driver-class-name: oracle.jdbc.driver.OracleDriver
  redis:
    host: 172.20.20.2
    port: 6379
    password: 87775236
    timeout: 3600ms #超时时间
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接 默认8
        max-wait: -1ms #默认-1 最大连接阻塞等待时间
        min-idle: 0 #最小空闲连接



test-cron: '0 */5 * * * ?'
